### ISSUE TITLE
Add support for kali-rolling

### ISSUE THREAD

**Issue by 0xicl33n** [RobertCNelson/linux-dev#41]
The problem when building on kali rolling :
```
+ Detected build host [Kali GNU/Linux Rolling]
+ host: [x86_64]
+ git HEAD commit: [9b9c936a2950210e70d9d1cd37e60088c0dff314]
Dependency check skipped, you are on your own.
-----------------------------
Unrecognized deb based system:
-----------------------------
Please cut, paste and email to: bugs@rcn-ee.com
-----------------------------
git: [9b9c936a2950210e70d9d1cd37e60088c0dff314]
git: [url=https://github.com/RobertCNelson/linux-dev]
uname -m: [x86_64]
lsb_release -a:
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        kali-rolling
Codename:       kali-rolling
-----------------------------
* Failed dependency check

root@lead:~# cat /etc/issue
Kali GNU/Linux Rolling \n \l
root@lead:~# uname -a
Linux lead 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux
```

Adding 
```
if [ "x${deb_distro}" = "kali-rolling" ] ; then
			#lsb_release -a
			#Distributor ID: Kali
			#Description:    Kali GNU/Linux Rolling
			#Release:        kali-rolling
			#Codename:       kali-rolling

			deb_distro="sid"
		fi
``` 

To `tools/host_det.sh` should fix this. I do not know if kali-rolling is sid or still jessie, from what i understand it is sid

**Comment by 0xicl33n** [comment]
@29242e2f19b8e4dc367554ad888a264f3184fa7b

**Comment by duchengyao** [comment]
Added 

        if [ "x${deb_distro}" = "kali-rolling" ] ; then
        ......
        deb_distro="sid"
        fi

but still not work

**Comment by RobertCNelson** [comment]
@0xicl33n & @duchengyao just missed an "x" in the comparsion, also tied it down to stretch as that's closer for "testing", sid is "unstable" so about a week earlier then "testing"..  i'll bump it to stretch+1 when stretch gets releasesed.

Regards

**Comment by duchengyao** [comment]
Thank you so much.

**Comment by 0xicl33n** [comment]
Ive attempted running this on kali rolling and it still doesnt work . In the meantime ive setup a specific build server running 2.0

Since the 2.0 iso files were removed from the official kali.org download page i had to find them myself

http://ftp.cc.uoc.gr/mirrors/linux/kali/kali-images/kali-2.0/

Heres a mirror if you need em too

**Comment by duchengyao** [comment]
Thanks ^_^

**Comment by duchengyao** [comment]
BTW, do you have the problem like [0002510: Beaglebone mouse crash](https://bugs.kali.org/view.php?id=2510)

**Comment by RobertCNelson** [comment]
@duchengyao force 'fbdev' with this xorg.conf

https://github.com/RobertCNelson/boot-scripts/blob/master/tools/graphics/ti-tilcdc.sh#L57-L79

The modesetting driver is broken on this device.

Regards,

**Comment by RobertCNelson** [comment]
btw, for background, it's easy to determine it's modesetting... When it does lock up, everything lock's up..

serial, gpio, ethernet, usb, (jtag even goes down..)

It's very easy to re-produce with jpeg images in any gtk2 application... something goes in the wrong place in memory...

Regards,

**Comment by duchengyao** [comment]
It is perfectly solved my problem. Thanks so much!!

Best wishes.
